package com.zergatul.scripting.lexer;

public enum TokenType {
    WHITESPACE,
    LEFT_PARENTHESES,
    RIGHT_PARENTHESES,
    LEFT_SQUARE_BRACKET,
    RIGHT_SQUARE_BRACKET,
    LEFT_CURLY_BRACKET,
    RIGHT_CURLY_BRACKET,
    DOT,
    COMMA,
    COLON,
    SEMICOLON,
    EXCLAMATION,
    PLUS,
    MINUS,
    ASTERISK,
    SLASH,
    PERCENT,
    IDENTIFIER,
    FALSE,
    TRUE,
    INTEGER_LITERAL,
    END_OF_FILE,
    EQUAL,
    QUESTION,
    BOOLEAN,
    INT,
    FLOAT,
    STRING,
    NEW,
    PLUS_EQUAL,
    MINUS_EQUAL,
    ASTERISK_EQUAL,
    SLASH_EQUAL,
    INVALID
}