package com.zergatul.scripting.binding;

import com.zergatul.scripting.ErrorCode;

public class BinderErrors {
    public static final ErrorCode CannotImplicitlyConvert = new ErrorCode("B001", "Cannot implicitly convert type '%s' to '%s'");
    public static final ErrorCode UnaryOperatorNotDefined = new ErrorCode("B002", "Operator '%s' cannot be applied to operand of type '%s'");
    public static final ErrorCode BinaryOperatorNotDefined = new ErrorCode("B003", "Operator '%s' cannot be applied to operands of type '%s' and '%s'");
    public static final ErrorCode IntegerConstantTooSmall = new ErrorCode("B004", "Integer constant is too small");
    public static final ErrorCode IntegerConstantTooLarge = new ErrorCode("B005", "Integer constant is too large");
    public static final ErrorCode CannotDetermineConditionalExpressionType = new ErrorCode("B006", "Type of conditional expression cannot be determined because there is no implicit conversion between '%s' and '%s'");
    public static final ErrorCode CannotApplyIndex = new ErrorCode("B007", "Cannot apply indexing with [] to an expression of type '%s'");
    public static final ErrorCode SymbolAlreadyDeclared = new ErrorCode("B008", "A symbol named '%s' is already defined in this or one of the parent scopes");
    public static final ErrorCode NameDoesNotExist = new ErrorCode("B009", "The name '%s' does not exist in the current context");
    public static final ErrorCode MemberDoesNotExist = new ErrorCode("B010", "'%s' does not contain a definition for '%s'");
    public static final ErrorCode FunctionExpected = new ErrorCode("B011", "Function expected");
    public static final ErrorCode NonInvocableMember = new ErrorCode("B012", "Non-invocable member '%s.%s' cannot be used like a method");
    public static final ErrorCode NoOverloadedMethods = new ErrorCode("B013", "No overload for method '%s' takes %d arguments");
    public static final ErrorCode NoOverloadedConstructors = new ErrorCode("B013", "No overload for constructor '%s' takes %d arguments");
    public static final ErrorCode ArgumentCountMismatch = new ErrorCode("B014", "Function '%s' expects %d arguments");
    public static final ErrorCode CannotCastArguments = new ErrorCode("B015", "Invalid arguments");
    public static final ErrorCode InvalidFloatConstant = new ErrorCode("B016", "Cannot parse float constant");
    public static final ErrorCode NoLoop = new ErrorCode("B017", "No enclosing loop out of which to break or continue");
    public static final ErrorCode CannotApplyIncDec = new ErrorCode("B018", "Cannot apply '%s' to operand of type '%s'");
    public static final ErrorCode NewSupportArraysOnly = new ErrorCode("B019", "new expression support only arrays");
    public static final ErrorCode InvalidArrayCreation = new ErrorCode("B020", "Array creation must have array size or array initializer");
    public static final ErrorCode ExpressionCannotBeSet = new ErrorCode("B021", "The left-hand side of an assignment must be a variable, property or indexer");
    public static final ErrorCode CannotIterate = new ErrorCode("B022", "foreach statement cannot operate on expression of type '%s'");
    public static final ErrorCode ForEachTypesNotMatch = new ErrorCode("B023", "foreach variable type and expression type doesn't match");
    public static final ErrorCode LambdaIsInvalidInCurrentContext = new ErrorCode("B024", "Lambda expression is invalid in this context");
    public static final ErrorCode NotFunction = new ErrorCode("B025", "Not a function");
    public static final ErrorCode CannotCastArgument = new ErrorCode("B026", "Argument '%d' cannot convert from '%s' to '%s'");
    public static final ErrorCode EmptyReturnStatement = new ErrorCode("B027", "Cannot return void");
    public static final ErrorCode AugmentedAssignmentInvalidType = new ErrorCode("B030", "'%s' operator on types '%s' and '%s' returns '%s', and it does not match with left side");
    public static final ErrorCode NotAllPathReturnValue = new ErrorCode("B031", "Not all code paths return a value");
    public static final ErrorCode CannotAwaitNonFuture = new ErrorCode("B032", "Only expressions with type Future<?> can be awaited");
    public static final ErrorCode InvalidCallee = new ErrorCode("B033", "Cannot call %s");
    public static final ErrorCode AwaitInNonAsyncContext = new ErrorCode("B034", "Cannot use 'await' in non-async context");
    public static final ErrorCode TypeNotDefined = new ErrorCode("B035", "Type '%s' is not defined");
    public static final ErrorCode LetEmptyCollection = new ErrorCode("B036", "Cannot infer type of empty array. Please use 'new' syntax or replace 'let' with explicit array type.");
    public static final ErrorCode CannotInferCollectionExpressionTypes = new ErrorCode("B037", "Cannot infer collection expression types: Type at position 0: '%s', type at position %d: '%s'.");
    public static final ErrorCode RefTypeNotSupported = new ErrorCode("B038", "ref type for '%s' is not supported");
    public static final ErrorCode JavaTypeDoesNotExist = new ErrorCode("B039", "Java type '%s' does not exist");
    public static final ErrorCode JavaTypeNotAllowed = new ErrorCode("B040", "%s");
    public static final ErrorCode IdentifierIsNotType = new ErrorCode("B041", "'%s' is not type");
    public static final ErrorCode MemberAlreadyDeclared = new ErrorCode("B042", "Member named '%s' already exists");
    public static final ErrorCode ConstructorAlreadyDeclared = new ErrorCode("B043", "Constructor with the same parameters already declared");
    public static final ErrorCode MethodAlreadyDeclared = new ErrorCode("B044", "Method with the same signature already declared");
    public static final ErrorCode ThisInvalidContext = new ErrorCode("B045", "'this' is invalid in this context");
    public static final ErrorCode LetInvalidContext = new ErrorCode("B046", "'let' is invalid in this context");
    public static final ErrorCode CastOperationNotAllowed = new ErrorCode("B047", "Implicit casting is not allowed for node of type %s");
    public static final ErrorCode InvalidRefExpression = new ErrorCode("B048", "Invalid ref expression");
    public static final ErrorCode LetUnboundLambda = new ErrorCode("B049", "Cannot assign lambda to 'let' variable");
    public static final ErrorCode ArgumentCountMismatch2 = new ErrorCode("B050", "Function expects %d arguments");
    public static final ErrorCode CannotUseInOperator = new ErrorCode("B051", "Cannot use 'in' operator, since type '%s' does not have defined method 'contains' with parameter of type '%s' and return type 'boolean'");
    public static final ErrorCode ExtensionMethodAlreadyDeclared = new ErrorCode("B052", "Extension method with the same signature already declared");
    public static final ErrorCode BaseClassNoParameterlessConstructor = new ErrorCode("B053", "Base class does not have parameterless constructor");
    public static final ErrorCode BaseClassAlreadyHasMember = new ErrorCode("B054", "Base class has member with the same name.");
    public static final ErrorCode MethodOverrideReturnMismatch = new ErrorCode("B055", "Base class has method with the same name and parameters, but different return type");
    public static final ErrorCode OverrideMissing = new ErrorCode("B056", "Method with the same signature is defined in the base class. Did you miss 'override'?");
    public static final ErrorCode NonVirtualOverride = new ErrorCode("B057", "Only 'abstract' or 'virtual' methods can have 'override'. Did you miss 'virtual' in the base class?");
    public static final ErrorCode BaseInvalidContext = new ErrorCode("B058", "'base' is invalid in this context");
    public static final ErrorCode CannotInstantiateAbstractClass = new ErrorCode("B059", "Cannot instantiate abstract class");
    public static final ErrorCode BaseInvalidUse = new ErrorCode("B060", "'base' is only allowed for method calls");
    public static final ErrorCode CannotOverrideFinal = new ErrorCode("B061", "Cannot override final method");
    public static final ErrorCode NoConstructors = new ErrorCode("B062", "No constructors exist for '%s'");
    public static final ErrorCode ClassCircularInheritance = new ErrorCode("B063", "Class circular inheritance");
    public static final ErrorCode NoDefaultValue = new ErrorCode("B064", "Type '%s' does not have default value, please assign value for this variable");

    public static final ErrorCode InternalError = new ErrorCode("B999", "Internal error: %s");
}