package com.zergatul.scripting.highlighting;

public enum SemanticTokenType {
    KEYWORD,
    IDENTIFIER,
    TYPE,
    BRACKET,
    SEPARATOR,
    OPERATOR,
    ARROW,
    NUMBER,
    STRING,
    COMMENT
}

/*
*           case IDENTIFIER -> IDENTIFIER;
            case LEFT_PARENTHESES, LEFT_CURLY_BRACKET, LEFT_SQUARE_BRACKET, RIGHT_PARENTHESES, RIGHT_CURLY_BRACKET,
                 RIGHT_SQUARE_BRACKET -> BRACKETS;
            case DOT, DOLLAR, COMMA, SEMICOLON, COLON -> SEPARATORS;
            case PLUS, PLUS_PLUS, PLUS_EQUAL, MINUS, MINUS_MINUS, MINUS_EQUAL, ASTERISK, ASTERISK_EQUAL, SLASH,
                 SLASH_EQUAL, PERCENT, PERCENT_EQUAL, AMPERSAND, AMPERSAND_AMPERSAND, AMPERSAND_EQUAL, PIPE, PIPE_PIPE,
                 PIPE_EQUAL, EQUAL, EQUAL_EQUAL, EQUAL_GREATER, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, EXCLAMATION,
                 EXCLAMATION_EQUAL, QUESTION -> OPERATORS;
            case BOOLEAN, INT8, INT16, INT, INT32, INT64, LONG, CHAR, FLOAT32, FLOAT, FLOAT64, STRING, IF, ELSE, BREAK, CONTINUE, WHILE, FOR, FOREACH, FALSE, TRUE, IN,
                 NEW, REF, RETURN, STATIC, VOID, ASYNC, AWAIT, LET, IS, AS, META_UNKNOWN, META_TYPE, META_TYPE_OF, CLASS, CONSTRUCTOR, THIS -> KEYWORD;
            case INTEGER_LITERAL, INTEGER64_LITERAL, FLOAT_LITERAL, INVALID_NUMBER -> NUMBERS;
            case CHAR_LITERAL, STRING_LITERAL -> STRINGS;
            case WHITESPACE, LINE_BREAK, END_OF_FILE, INVALID -> INVALID;
            case COMMENT -> COMMENTS;
* */